export const IconData: Map<string, any> = new Map<string, any>([
    ['', ''],
    ['business', { source: '/assets/icons/business.svg', w: 1.085, h: 1}],
    ['business-view', { source: '/assets/icons/view_business.svg', w: 1.142, h: 1}],
    ['circle-check', { source: '/assets/icons/circle_check.svg', w: 1, h: 1}],
    ['circle-cross', { source: '/assets/icons/circle_cross.svg', w: 1, h: 1}],
    ['comment', { source: '/assets/icons/comment.svg', w: 1, h: 1}],
    ['dashboard', { source: '/assets/icons/dashboard.svg', w: 1, h: 1}],
    ['document', { source: '/assets/icons/document.svg', w: 0.7894, h: 1}],
    ['document-edit', { source: '/assets/icons/document_edit.svg', w: 1, h: 1.027}],
    ['document-send', { source: '/assets/icons/document_sent.svg', w: 0.868, h: 1}],
    ['document-check', { source: '/assets/icons/document_check.svg', w: 0.921, h: 1}],
    ['trash', { source: '/assets/icons/trash.svg', w: 0.7368, h: 1}],
    ['folder-documents', { source: '/assets/icons/folder_documents.svg', w: 1.3, h: 1}],
    ['folder-validate', { source: '/assets/icons/folder_validate.svg', w: 1.3, h: 1}],
    ['info', { source: '/assets/icons/info.svg', w: 1, h: 1}],
    ['person', { source: '/assets/icons/person.svg', w: 1, h: 1}],
    ['list', { source: '/assets/icons/list.svg', w: 0.921, h: 1}],
    ['logout', { source: '/assets/icons/logout.svg', w: 1, h: 1}],
    ['rigth-arrow', { source: '/assets/icons/right_arrow.svg', w: 1, h: 1}]
]);